SELECT * FROM (SELECT c.ID, c.EMAIL_ADDR AS EMAIL_ADDRESS_, c.TIER, 
ROW_NUMBER() OVER (PARTITION BY c.EMAIL_ADDR ORDER BY c.TIER ASC) AS ROWNUMBER --pick the more valuable tier 
FROM pdb.S_CAMP_CON_VW a, pdb.contact b, pdb.contact_brand c 
WHERE a.LOADED_CCN=b.CCN AND a.LOADED_CCN=C.CCN AND b.ccn=c.ccn 
AND ((a.CAMPAIGN_CODE = 'PE9CS079A' AND a.LOAD_NUMBER = '1') 
OR (a.CAMPAIGN_CODE = 'PE9CS079B' AND a.LOAD_NUMBER = '1') 
OR (a.CAMPAIGN_CODE = 'PE9CS079C' AND a.LOAD_NUMBER = '1') 
OR (a.CAMPAIGN_CODE = 'PE9CS079D' AND a.LOAD_NUMBER = '1') 
OR (a.CAMPAIGN_CODE = 'PE9CS079W' AND a.LOAD_NUMBER = '1')
OR (a.CAMPAIGN_CODE = 'PE9CS079E' AND a.LOAD_NUMBER = '1') 
OR (a.CAMPAIGN_CODE = 'PE9CS079V' AND a.LOAD_NUMBER = '1')) 
AND c.brand ='PC') 
WHERE ROWNUMBER = 1
